### ISSUE TITLE
tctl plugins

### ISSUE THREAD

**Issue by dtornow** [temporalio/proposals#43]
**Author**: Dominik Tornow, Ruslan Aksenov

### Summary of the feature being proposed

- Extend tctl with plugins (like [kubectl](https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/))
- Eventually, provide a plugin directory (like [krew](https://krew.sigs.k8s.io))

### What value does this feature bring to Temporal?

tctl provides the core apis to interact with temporal. tctl plugins provide additional behaviors, possibly combining and/or extending the core apis.

A tctl plugin is a standalone executable, whose name is prefixed with `tctl-`, located anywhere on the PATH. For example, the command `tctl foo` will invoke the plugin `tctl-foo` if the executable `tctl-foo` is located anywhere on the PATH.

**Example: Plugin tctl-foo**

```
#!/bin/bash

# optional argument handling
if [[ "$1" == "version" ]]
then
    echo "1.0.0"
    exit 0
fi

echo "I am a plugin named tctl-foo"
```

```
$ tctl foo version
> 1.0.0

$ tctl foo
> I am a plugin named tctl-foo
```

**Note**

Any Similarities with [kubectl](https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/) are completely and entirely **not** accidental.

### Are you willing to implement this feature yourself?

The temporal team

**Comment by dtornow** [comment]
![Plugins](https://user-images.githubusercontent.com/580718/135539448-f48f34dd-06e3-465c-82ab-8a611cc1b9ef.jpg)

**Comment by bergundy** [comment]
I feel like this proposal requires some use cases to understand the motivation behind it.

**Comment by protochron** [comment]
This seems like an interesting idea for being able to extend `tctl` for unknown use cases. I could see it being handy for ex. implementing the client side of a custom auth scheme.

Replicating what kubectl seems like a decent model to start with. It's probably overkill, but have you looked at doing something similar to what [Hashicorp does for plugins](https://github.com/hashicorp/go-plugin)? The immediate downside is the complexity inherent in writing a plugin, but being able to communicate back and forth with a plugin beyond just executing it could be useful depending on the use case.

**Comment by mfateev** [comment]
We[ already use ](https://github.com/temporalio/samples-go/tree/master/cryptconverter/plugin)Hashicorp plugin for DataConverter. 

For me, plugin is something that leverages the core program capabilities. The proposal executes each plugin completely independently. How each plugin is going to benefit from some shared features like auth, etc.?

**Comment by dtornow** [comment]
> The proposal executes each plugin completely independently

Correct, each plugin executes independently

> How each plugin is going to benefit from some shared features like auth, etc.?

A common pattern in the context of Kubernetes is that the kubectl plugin itself calls kubectl, therefore executing "in the current kubectl context".

This is not a "deep" but rather a "shallow" integration. However, on the flip side, plugins are simple to develop and distribute

An example could be a custom visualization of a workflow history:

**tctl-visualize**

```
#!/bin/bash

tctl workflow showid $1 | custom-visualization -f png -o $1.png

```

```
tctl visualize 3ea6b242-b23c-4279-bb13-f215661b4717
```

**Comment by Sushisource** [comment]
I like the subprocess approach for simplicity. It allows language flexibility (on both sides -- maybe one day `tctl` gets the Rust treatment).

The downside, which Max gets at, is exposing everything a plugin might ever need as `stdout` from `tctl` possibly requires a lot of commands that no user would ever call directly, and on top of that introduces all these parsing concerns. 

To oversimplify a bit: Either your problem is somewhat trivially solved (Output from `tctl` is simple), or you have to parse a lot, or you modify tctl to have simple output for specifically what you're trying to do (obviating the point of a plugin in the first place).

Not to be too obnoxious, but maybe this is a really good fit for WASM. `tctl` can run plugins using https://github.com/wasmerio/wasmer-go  -- those plugins could make used of a defined set of functions `tctl` exposes which can represent its public interface: https://docs.wasmer.io/integrations/examples/imports-and-exports - Long run we could also easily offer a precompiled set of plugins that ship with tctl or a registry. This works in both Go and Rust, but is a bit prettier in Rust (mainly authoring plugins).

Anyway, just some ideas to throw out there.

**Comment by cretz** [comment]
Just seeing this now, one benefit of using a plugin approach over a separate process approach is leveraging all the flags in `tctl` already. For example, I personally would like a "with client options" plugin that receives client options based on the normal tctl commands. Right now I have to copy existing tctl approaches for client options.

I don't think you want everything a plugin ever needs. Instead define the types of plugins and/or plugin options as needs arise. I think a clear need at least at first is the ability to receive all the options needed to connect to the Temporal server from other processes using `tctl` as the frontdoor w/ consistent flags.

**Comment by cretz** [comment]
After self-reflection, I recant my above statement and support sub-processes like `kubectl` does.

**Comment by feedmeapples** [comment]
discussed directly with people in this thread and ended up with the sub-processes approach. Binaries in PATH that have `tctl-` prefix will be considered tctl plugins

**Comment by feedmeapples** [comment]
fyi this is technically implemented in tctl v2 https://github.com/temporalio/tctl#trying-out-new-tctl-v200-beta-with-updated-ux

There are still some UX improvements i want to make before documenting the feature / closing the issue

**Comment by josh-berry** [comment]
We're working on replacing tctl with https://github.com/temporalio/cli, so this will unfortunately not be worked on. If there are specific/motivating use cases for plugins for Temporal CLI, I'd be happy to consider them in a different proposal, but I'd like to see some concrete examples that illustrate why a plugin approach is preferred to wrapping Temporal CLI in a shell script (for example).

Also, I'm much more comfortable with simple solutions that allow plugin authors to use their preferred languages, tooling, etc., all of which necessitates a separate process. More heavyweight or "framework-y" type designs would need a correspondingly more compelling use case, because they are much harder to develop and maintain.
